version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11
    working_directory: ~/keenethics
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Fix host authenticity for 107.170.121.178
          command: ssh-keyscan 107.170.121.178 >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "98:07:43:e3:59:01:09:83:3d:69:1c:eb:ca:17:33:78"
      - run:
          name: Install rsync
          command: sudo apt install rsync
      - run: yarn deploy
